services:
  postgres:
    image: postgres:17

    container_name: rupp-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hon979471197
      POSTGRES_DB: rupp_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend

    container_name: rupp-backend

    depends_on:
      - postgres

    ports:
      - "5050:5050"

    env_file:
      - ./backend/.env

volumes:
  postgres_data:
