FROM node:22-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y openssl

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

CMD ["npm", "start"]